import React from 'react';
import { setup, Store, Sidenote, InlineAnchor, AnchorBase, actions } from 'sidenotes';
import { deselectSidenote } from 'sidenotes/dist/src/store/ui/actions';
import { useStore } from 'react-redux';

import 'sidenotes/dist/sidenotes.css';

var store: Store;

const docId = 'article';
const baseAnchor = 'anchor';
const blue = 'blue';
const red = 'red';
const green = 'green';

type Test = {
    title: string
}

function App({ title }: Test) {

    store = useStore();
    const deselect = () => store.dispatch(deselectSidenote(docId));

    return (
        <>

            <article id={docId} onClick={deselect}>
                <h1>Genesis 1</h1>

                <AnchorBase anchor={baseAnchor} className="greenBase">
                    <div className="chapter ch1 frag0" data-usfm="GEN.1">
                        <div className="s"><span className="heading">The History of Creation</span></div>
                        <div className="p"><span className="verse v1" data-usfm="GEN.1.1"><span className="label">1</span><span className="content">In the </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 102:25; Is. 40:21; (John 1:1-3; Heb. 1:10)</span></span><span className="content">beginning </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 2:4; (Ps. 8:3; 89:11; 90:2); Is. 44:24; Acts 17:24; Rom. 1:20; (Heb. 1:2; 11:3); Rev. 4:11</span></span><span className="content">God created the heavens and the earth. </span></span><span className="verse v2" data-usfm="GEN.1.2"><span className="label">2</span><span className="content">The earth was </span><span className="note x"><span className="label">#</span><span className=" body">Jer. 4:23</span></span><span className="content">without form, and void; and darkness </span><span className="it"><span className="content">was</span></span><span className="content"> on the face of the deep. </span><span className="note x"><span className="label">#</span><span className=" body">(Gen. 6:3); Job 26:13; Ps. 33:6; 104:30; Is. 40:13, 14</span></span><span className="content">And the Spirit of God was hovering over the face of the waters.</span></span></div>
                        <div className="p"><span className="verse v3" data-usfm="GEN.1.3"><span className="label">3</span><span className="note x"><span className="label">#</span><span className=" body">Ps. 33:6, 9</span></span><span className="content">Then God said, </span><span className="note x"><span className="label">#</span><span className=" body">2 Cor. 4:6</span></span><span className="content">"Let there be </span><span className="note x"><span className="label">#</span><span className=" body">(Heb. 11:3)</span></span><span className="content">light"; and there was light. </span></span><span className="verse v4" data-usfm="GEN.1.4"><span className="label">4</span><span className="content">And God saw the light, that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good; and God divided the light from the darkness. </span></span><span className="verse v5" data-usfm="GEN.1.5"><span className="label">5</span><span className="content">God called the light Day, and the </span><span className="note x"><span className="label">#</span><span className=" body">Job 37:18; Ps. 19:2; 33:6; 74:16; 104:20; 136:5; Jer. 10:12</span></span><span className="content">darkness He called Night. So the evening and the morning were the first day.</span></span></div>
                        <div className="p"><span className="verse v6" data-usfm="GEN.1.6"><span className="label">6</span><span className="content">Then God said, </span><span className="note x"><span className="label">#</span><span className=" body">Job 37:18; Jer. 10:12; 2 Pet. 3:5</span></span><span className="content">"Let there be a firmament in the midst of the waters, and let it divide the waters from the waters." </span></span><span className="verse v7" data-usfm="GEN.1.7"><span className="label">7</span><span className="content">Thus God made the firmament, </span><span className="note x"><span className="label">#</span><span className=" body">Job 38:8-11; Prov. 8:27-29</span></span><span className="content">and divided the waters which </span><span className="it"><span className="content">were</span></span><span className="content"> under the firmament from the waters which </span><span className="it"><span className="content">were</span></span><span className="content">  </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 148:4</span></span><span className="content">above the firmament; and it was so. </span></span><span className="verse v8" data-usfm="GEN.1.8"><span className="label">8</span><span className="content">And God called the firmament Heaven. So the evening and the morning were the second day.</span></span></div>
                        <div className="p"><span className="verse v9" data-usfm="GEN.1.9"><span className="label">9</span><span className="content">Then God said, </span><span className="note x"><span className="label">#</span><span className=" body">Job 26:10; Ps. 104:6-9; Prov. 8:29; Jer. 5:22; 2 Pet. 3:5</span></span><span className="content">"Let the waters under the heavens be gathered together into one place, and </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 24:1, 2; 33:7; 95:5</span></span><span className="content">let the dry </span><span className="it"><span className="content">land</span></span><span className="content"> appear"; and it was so. </span></span><span className="verse v10" data-usfm="GEN.1.10"><span className="label">10</span><span className="content">And God called the dry </span><span className="it"><span className="content">land</span></span><span className="content"> Earth, and the gathering together of the waters He called Seas. And God saw that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good.</span></span></div>
                        <div className="p"><span className="verse v11" data-usfm="GEN.1.11"><span className="label">11</span><span className="content">Then God said, <InlineAnchor sidenote={blue} className="blue">"Let the earth</InlineAnchor></span><span className="note x"><span className="label">#</span><span className=" body">Ps. 65:9-13; 104:14; Heb. 6:7</span></span><span className="content">bring forth grass, the herb </span><span className="it"><span className="content">that</span></span><span className="content"> yields seed, </span><span className="it"><span className="content">and</span></span><span className="content"> the </span><span className="note x"><span className="label">#</span><span className=" body">2 Sam. 16:1; Luke 6:44</span></span><span className="content">fruit tree </span><span className="it"><span className="content">that</span></span><span className="content"> yields fruit according to its kind, whose seed </span><span className="it"><span className="content">is</span></span><span className="content"> in itself, on the earth"; and it was so. </span></span><span className="verse v12" data-usfm="GEN.1.12"><span className="label">12</span><span className="content">And the earth brought forth grass, the herb </span><span className="it"><span className="content">that</span></span><span className="content"> yields seed according to its kind, and the tree </span><span className="it"><span className="content">that</span></span><span className="content"> yields fruit, whose seed </span><span className="it"><span className="content">is</span></span><span className="content"> in itself according to its kind. And God saw that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good. </span></span><span className="verse v13" data-usfm="GEN.1.13"><span className="label">13</span><span className="content">So the evening and the morning were the third day.</span></span></div>
                        <div className="p"><span className="verse v14" data-usfm="GEN.1.14"><span className="label">14</span><span className="content">Then God said, "Let there be </span><span className="note x"><span className="label">#</span><span className=" body">Deut. 4:19; Ps. 74:16; 136:5-9</span></span><span className="content">lights in the firmament of the heavens to divide the day from the night; and let them be for signs and </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 104:19</span></span><span className="content">seasons, and for days and years; </span></span><span className="verse v15" data-usfm="GEN.1.15"><span className="label">15</span><span className="content">and let them be for lights in the firmament of the heavens to give light on the earth"; and it was so. </span></span><span className="verse v16" data-usfm="GEN.1.16"><span className="label">16</span><span className="content">Then God made two great lights: the </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 136:8</span></span><span className="content">greater light to rule the day, and the </span><span className="note x"><span className="label">#</span><span className=" body">Deut. 17:3; Ps. 8:3</span></span><span className="content">lesser light to rule the night. </span><span className="it"><span className="content">He</span></span><span className="content">  </span><span className="it"><span className="content">made</span></span><span className="content">  </span><span className="note x"><span className="label">#</span><span className=" body">Deut. 4:19; Job 38:7; Is. 40:26</span></span><span className="content">the stars also. </span></span><span className="verse v17" data-usfm="GEN.1.17"><span className="label">17</span><span className="content">God set them in the firmament of the </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 15:5; Jer. 33:20, 25</span></span><span className="content">heavens to give light on the earth, </span></span><span className="verse v18" data-usfm="GEN.1.18"><span className="label">18</span><span className="content">and to </span><span className="note x"><span className="label">#</span><span className=" body">Jer. 31:35</span></span><span className="content">rule over the day and over the night, and to divide the light from the darkness. And God saw that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good. </span></span><span className="verse v19" data-usfm="GEN.1.19"><span className="label">19</span><span className="content">So the evening and the morning were the fourth day.</span></span></div>
                        <div className="p"><span className="verse v20" data-usfm="GEN.1.20"><span className="label">20</span><span className="content">Then God said, "Let the waters abound with an abundance of living creatures, and let birds fly above the earth across the face of the firmament of the heavens." </span></span><span className="verse v21" data-usfm="GEN.1.21"><span className="label">21</span><span className="content">So </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 104:25-28</span></span><span className="content">God created great sea creatures and every living thing that moves, with which the waters abounded, according to their kind, and every winged bird according to its kind. And God saw that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good. </span></span><span className="verse v22" data-usfm="GEN.1.22"><span className="label">22</span><span className="content">And God blessed them, saying, </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 8:17</span></span><span className="content">"Be fruitful and multiply, and fill the waters in the seas, and let birds multiply on the earth." </span></span><span className="verse v23" data-usfm="GEN.1.23"><span className="label">23</span><span className="content">So the evening and the morning were the fifth day.</span></span></div>
                        <div className="p"><span className="verse v24" data-usfm="GEN.1.24"><span className="label">24</span><span className="content">Then God said, <InlineAnchor sidenote={red} className="red">"Let the earth</InlineAnchor> bring forth the living creature according to its kind: cattle and creeping thing and beast of the earth, </span><span className="it"><span className="content">each</span></span><span className="content"> according to its kind"; and it was so. </span></span><span className="verse v25" data-usfm="GEN.1.25"><span className="label">25</span><span className="content">And God made the beast of the earth according to its kind, cattle according to its kind, and everything that creeps on the earth according to its kind. And God saw that </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> good.</span></span></div>
                        <div className="p"><span className="verse v26" data-usfm="GEN.1.26"><span className="label">26</span><span className="content">Then God said, </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 9:6; Ps. 100:3; Eccl. 7:29; (Eph. 4:24); James 3:9</span></span><span className="content">"Let Us make man in Our image, according to Our likeness; </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 9:2; Ps. 8:6-8</span></span><span className="content">let them have dominion over the fish of the sea, over the birds of the air, and over the cattle, over all the earth and over every creeping thing that creeps on the earth." </span></span><span className="verse v27" data-usfm="GEN.1.27"><span className="label">27</span><span className="content">So God created man </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 5:2; 1 Cor. 11:7</span></span><span className="content">in His </span><span className="it"><span className="content">own</span></span><span className="content"> image; in the image of God He created him; </span><span className="note x"><span className="label">#</span><span className=" body">Matt. 19:4; (Mark 10:6-8)</span></span><span className="content">male and female He created them. </span></span><span className="verse v28" data-usfm="GEN.1.28"><span className="label">28</span><span className="content">Then God blessed them, and God said to them, </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 9:1, 7; Lev. 26:9</span></span><span className="content">"Be fruitful and multiply; fill the earth and </span><span className="note x"><span className="label">#</span><span className=" body">1 Cor. 9:27</span></span><span className="content">subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth."</span></span></div>
                        <div className="p"><span className="verse v29" data-usfm="GEN.1.29"><span className="label">29</span><span className="content">And God said, "See, I have given you every herb </span><span className="it"><span className="content">that</span></span><span className="content"> yields seed which </span><span className="it"><span className="content">is</span></span><span className="content"> on the face of all the earth, and every tree whose fruit yields seed; </span><span className="note x"><span className="label">#</span><span className=" body">Gen. 9:3; Ps. 104:14, 15</span></span><span className="content">to you it shall be for food. </span></span><span className="verse v30" data-usfm="GEN.1.30"><span className="label">30</span><span className="content">Also, to </span><span className="note x"><span className="label">#</span><span className=" body">Ps. 145:15</span></span><span className="content">every beast of the earth, to every </span><span className="note x"><span className="label">#</span><span className=" body">Job 38:41</span></span><span className="content">bird of the air, and to everything that creeps on the earth, in which </span><span className="it"><span className="content">there</span></span><span className="content">  </span><span className="it"><span className="content">is</span></span><span className="content"> life, </span><span className="it"><span className="content">I</span></span><span className="content">  </span><span className="it"><span className="content">have</span></span><span className="content">  </span><span className="it"><span className="content">given</span></span><span className="content"> every green herb for food"; and it was so. </span></span><span className="verse v31" data-usfm="GEN.1.31"><span className="label">31</span><span className="content">Then </span><span className="note x"><span className="label">#</span><span className=" body">(Ps. 104:24; 1 Tim. 4:4)</span></span><span className="content">God saw everything that He had made, and indeed </span><span className="it"><span className="content">it</span></span><span className="content">  </span><span className="it"><span className="content">was</span></span><span className="content"> very good. So the evening and the morning were the sixth day.</span></span></div>
                    </div>
                </AnchorBase>

                <p className="notice">Scripture taken from the New King James Version®. Copyright © 1982 by Thomas Nelson. Used by permission. All rights reserved.</p>

                <div className="sidenotes">
                    <Sidenote sidenote={blue} base={baseAnchor}>
                        <div style={{ width: 280, height: 150, backgroundColor: 'blue' }} />
                    </Sidenote>
                    <Sidenote sidenote={red} base={baseAnchor}>
                        <div style={{ width: 280, height: 100, backgroundColor: 'red' }} />
                    </Sidenote>
                    {/* <Sidenote sidenote={green} base={baseAnchor}>
                        <div style={{ width: 280, height: 100, backgroundColor: 'green' }}>
                            Attached to sidenote base.
                        </div>
                    </Sidenote> */}
                </div>

            </article>
        </>
    );
}

export default App;